server:
  port: 9001


spring:
  application:
    name: cloud-order-service


eureka:
  client:
    register-with-eureka: true   #自己作为客户端不需要注册进eureka
    service-url:
      defaultZone: http://localhost:7001/eureka #,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order${server.port}
    prefer-ip-address: true  #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 1  #向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 2 #收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除

ribbon:
  ReadTimeout: 5000 #建立连接的超时设置5秒
  ConnectTimeout: 5000 #调用服务超时5秒

logging:
  level:
    com.demo.springcloud.order.feign.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true
